### PR TITLE
bug: Handle private networks as trusted proxies

### LINKED ISSUE #51: Automatically filter private networks from remote IP lookup
Currently, `get_remote` does not filter private network addresses. These include

10.0.0.0/8
172.16.0.0/12
192.168.0.0/16
127.0.0.1/32

### PR DESCRIPTION
**Pull request by jrconlin**
Local private networks should be automatically considered proxies and
skipped for metadata lookup.

Closes #51

### CODE REVIEW

File: channelserver/src/main.rs [hunk 1]
```diff
@@ -165,22 +165,39 @@ fn main() {
...
+                // into a CIDR by giving it a single address scope.
+                let mut fixed = proxy.to_owned();
+                if !proxy.contains("/") {
+                    fixed = format!("{}/32", proxy);
+                    debug!(log.log, "Fixing single address {}", fixed);
+                }
+                match fixed.parse::<ipnet::IpNet>() {
+                    Ok(addr) => trusted_list.push(addr),
+                    Err(err) => {
+                        error!(logger.log, "Ignoring unparsable IP address \"{}\"", proxy);
```
Comment (pjenvey) [inline channelserver/src/main.rs]: nit: don't forget raw strings
```suggestion
                        error!(logger.log, r#"Ignoring unparsable IP address "{}""#, proxy);
```

File: channelserver/src/meta.rs [hunk 2]
```diff
@@ -127,14 +127,10 @@ fn get_ua(
     None
 }
 
-fn is_trusted_proxy(proxy_list: &[IpNet], host: &str) -> Result<bool, HandlerError> {
+fn is_trusted_proxy(proxy_list: &[IpNet], host: &IpAddr) -> Result<bool, HandlerError> {
```
Comment (pjenvey) [inline channelserver/src/meta.rs]: no need for a Result<bool> now, this can just return a bool (this could also be a one liner: `proxy_list.iter().any(|range| range.contains(host))`)

File: channelserver/src/meta.rs [hunk 3]
```diff
@@ -127,14 +127,10 @@ fn get_ua(
...
     // Return if an address is NOT part of the allow list
```
Comment (pjenvey) [inline channelserver/src/meta.rs]: did I read this comment wrong or is it describing the opposite of what's happening?

File: channelserver/src/main.rs (hunk 1 above)
Comment (jrconlin) [reply channelserver/src/main.rs]: honestly, I do. Frequently. Thanks!

File: channelserver/src/meta.rs (hunk 3 above)
Comment (jrconlin) [reply channelserver/src/meta.rs]: Sigh, no, you read it right. It's wrong. Thanks!
